### ISSUE TITLE
I don't think this person is developing any of their modules anymore. 

### ISSUE THREAD

**Issue by Flintwyrm** [Brunhine/TurnMarker#24]
I have not seen any activity from them and it is impossible to contact this Dev. They are not even taking messages through discord.

**Comment by lozalojo** [comment]
I sent a PR a couple of weeks ago, maybe the people at The League of Extraordinary Foundry Developers can take the project since it has been abandoned.

**Comment by kckaiwei** [comment]
I've merged in the bugfixes + translations into my own fork after I added a new feature, since I have an interest in what this module has to offer. Here's my fork if you're interested.

https://github.com/kckaiwei/TurnMarker

**Comment by lozalojo** [comment]
If you plan to maintain it from now on, I'd suggest to rename to turnmaker-alt and to upload it to Foundry web, as others have done like token-tooltip-alt

**Comment by kckaiwei** [comment]
That's a good idea. I'll do that. Didn't know what other people have been doing till now. Nice to see you're a part of this module too :)

https://github.com/kckaiwei/TurnMarker-alt

**Comment by lozalojo** [comment]
I will PR an updated spanish translation soon, also I've reported a bug

**Comment by Flintwyrm** [comment]
I believe some one has take thin and its in a different branch
