### ISSUE TITLE
[BUG] Shown targets not displaying correctly

### ISSUE THREAD

**Issue by Jonwh25** [Brunhine/TurnMarker#7]
**Describe the bug**
_A clear and concise description of what the bug is._

**Environment Details**
Foundry VTT Version: 0.6.0
Turn Marker Version: 2.6.7

**To Reproduce**
player selects target
target not displayed to GM.

**Expected behavior**
When a player selects a target I am not seeing who they are targeting. I have disabled all the other modules and it seems to be this module that has the problem.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Comment by jaltepeter** [comment]
Turn Marker provides no functionality for or with the targeting system. Your issue may be with another module.
